# Generated by Django 3.2 on 2021-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_url',
            field=models.URLField(default='http://localhost:8000', max_length=255),
            preserve_default=False,
        ),
    ]
