# Generated by Django 3.2 on 2021-04-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('fb_link', models.URLField(max_length=255)),
                ('insta_link', models.URLField(max_length=255)),
                ('photo', models.ImageField(upload_to='meadia/team/%Y/%M/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
