# Generated by Django 3.2 on 2021-04-17 09:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubers',
            name='camera_type',
            field=models.CharField(choices=[('Cannon', 'Cannon'), ('Nikon', 'Nikon'), ('Sony', 'Sony'), ('Red', 'Red'), ('sony', 'sony'), ('Panasonic', 'Panasonic'), ('Fuji', 'Fuji'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='category',
            field=models.CharField(choices=[('Code', 'Code'), ('Mobile_review', 'Mobile_review'), ('Vlog', 'Vlog'), ('Gaming', 'Gaming'), ('Flim_making', 'Flim_making'), ('Cooking', 'Cooking')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
